# Generated by Django 5.2 on 2025-04-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='giriş',
            new_name='giris',
        ),
    ]
